In [9]:
import numpy as np
import pandas as pd 
data = {
    "Normal": [67, 69, 70, 62, 63, 67, 65, 59, 68, 66, 60, 65, 67, 63, 64, 65, 69, 60, 61, 67, 66, 64, 65, 68, 66, 62, 64, 67, 70, 63, 66, 65, 63, 66, 61, 65, 63, 63, 66, 66, 64, 64, 62, 67, 62, 66, 63, 66, 65, 63],
    "Skewed-right": [31, 40, 43, 24, 25, 40, 29, 30, 24, 30, 36, 29, 35, 38, 35, 55, 46, 55, 40, 36, 28, 30, 29, 26, 19, 26, 40, 40, 26, 19, 20, 19, 26, 34, 38, 34, 25, 25, 28, 34, 28, 34, 26, 28, 25, 24, 28, 31, 24, 28],
    "Skewed-left": [102, 87, 104, 55, 75, 70, 90, 75, 95, 80, 73, 66, 79, 93, 60, 84, 89, 73, 89, 73, 85, 98, 72, 79, 92, 35, 76, 71, 63, 90, 85, 72, 82, 63, 85, 72, 97, 82, 85, 93, 85, 73, 83, 92, 81, 92, 77, 81, 92, 77],
    "Uniform": [12.1, 11.6, 11.6, 12.1, 11.6, 12.4, 12.1, 11.6, 12.1, 11.7, 12.3, 12.3, 11.9, 12.0, 12.4, 12.2, 12.4, 12.2, 12.3, 12.3, 11.9, 12.0, 12.4, 12.2, 12.4, 12.3, 12.0, 12.1, 12.3, 12.5, 12.0, 12.5, 12.5, 12.3, 12.0, 12.0, 11.8, 12.4, 11.9, 12.5, 11.8, 11.7, 11.7, 12.0, 12.5, 12.0, 12.0, 12.0, 12.0, 12.0]
}
df = pd.DataFrame(data)
df

    Normal  Skewed-right  Skewed-left  Uniform
0       67            31          102     12.1
1       69            40           87     11.6
2       70            43          104     11.6
3       62            24           55     12.1
4       63            25           75     11.6
5       67            40           70     12.4
6       65            29           90     12.1
7       59            30           75     11.6
8       68            24           95     12.1
9       66            30           80     11.7
10      60            36           73     12.3
11      65            29           66     12.3
12      67            35           79     11.9
13      63            38           93     12.0
14      64            35           60     12.4
15      65            55           84     12.2
16      69            46           89     12.4
17      60            55           73     12.2
18      61            40           89     12.3
19      67            36           73     12.3
20      66            28           85     11.9
21      64            30           98     12.0
22      65            29           72     12.4
23      68            26           79     12.2
24      66            19           92     12.4
25      62            26           35     12.3
26      64            40           76     12.0
27      67            40           71     12.1
28      70            26           63     12.3
29      63            19           90     12.5
30      66            20           85     12.0
31      65            19           72     12.5
32      63            26           82     12.5
33      66            34           63     12.3
34      61            38           85     12.0
35      65            34           72     12.0
36      63            25           97     11.8
37      63            25           82     12.4
38      66            28           85     11.9
39      66            34           93     12.5
40      64            28           85     11.8
41      64            34           73     11.7
42      62            26           83     11.7
43      67            28           92     12.0
44      62            25           81     12.5
45      66            24           92     12.0
46      63            28           77     12.0
47      66            31           81     12.0
48      65            24           92     12.0
49      63            28           77     12.0

In [45]:
import numpy as np


def calculate_moments(data):
    for key, values in data.items():
        values = np.array(values)
        mean = np.mean(values)
        second_moment = np.mean(values**2)
        third_moment = np.mean(values**3)
        fourth_moment = np.mean(values**4)
        
        print(f"{key} Moments:")
        print(f"  1st Moment of Mean: {mean:.2f}")
        print(f"  2nd Moment of Mean: {second_moment:.2f}")
        print(f"  3rd Moment of Mean: {third_moment:.2f}")
        print(f"  4th Moment of Mean: {fourth_moment:.2f}\n")

calculate_moments(data)

Normal Moments:
  1st Moment of Mean: 64.76
  2nd Moment of Mean: 4200.28
  3rd Moment of Mean: 272840.96
  4th Moment of Mean: 17749897.48

Skewed-right Moments:
  1st Moment of Mean: 31.26
  2nd Moment of Mean: 1041.70
  3rd Moment of Mean: 37106.58
  4th Moment of Mean: 1413717.46

Skewed-left Moments:
  1st Moment of Mean: 80.44
  2nd Moment of Mean: 6627.64
  3rd Moment of Mean: 556627.72
  4th Moment of Mean: 47518235.80

Uniform Moments:
  1st Moment of Mean: 12.10
  2nd Moment of Mean: 146.43
  3rd Moment of Mean: 1773.26
  4th Moment of Mean: 21483.86

In [43]:
def calculate_moments(data):
    for key, values in data.items():
        mean = np.mean(values)
        centered_values = np.array(values) - mean 

        print(f"{key} Moments about Mean:")
        print(f"  1st Moment: {np.mean(centered_values):.2f}")
        print(f"  2nd Moment: {np.mean(centered_values**2):.2f}")
        print(f"  3rd Moment: {np.mean(centered_values**3):.2f}")
        print(f"  4th Moment: {np.mean(centered_values**4):.2f}\n")

calculate_moments(data)

Normal Moments about Mean:
  1st Moment: -0.00
  2nd Moment: 6.42
  3rd Moment: -1.00
  4th Moment: 107.70

Skewed-right Moments about Mean:
  1st Moment: -0.00
  2nd Moment: 64.51
  3rd Moment: 509.72
  4th Moment: 16841.82

Skewed-left Moments about Mean:
  1st Moment: 0.00
  2nd Moment: 157.05
  3rd Moment: -1765.27
  4th Moment: 120545.81

Uniform Moments about Mean:
  1st Moment: -0.00
  2nd Moment: 0.07
  3rd Moment: -0.00
  4th Moment: 0.01

In [52]:
  female_heights = {"Normal": [67, 69, 70, 62, 63, 67, 65, 59, 68, 66, 60, 65, 67, 63, 64, 65, 69, 60, 61, 67, 66, 64, 65, 68, 66, 62, 64, 67, 70, 63, 66, 65, 63, 66, 61, 65, 63, 63, 66, 66, 64, 64, 62, 67, 62, 66, 63, 66, 65, 63],}
df = pd.DataFrame(female_heights)
df

    Normal
0       67
1       69
2       70
3       62
4       63
5       67
6       65
7       59
8       68
9       66
10      60
11      65
12      67
13      63
14      64
15      65
16      69
17      60
18      61
19      67
20      66
21      64
22      65
23      68
24      66
25      62
26      64
27      67
28      70
29      63
30      66
31      65
32      63
33      66
34      61
35      65
36      63
37      63
38      66
39      66
40      64
41      64
42      62
43      67
44      62
45      66
46      63
47      66
48      65
49      63

In [72]:
import numpy as np

female_heights = {
    "Normal": [67, 69, 70, 62, 63, 67, 65, 59, 68, 66, 60, 65, 67, 63, 64, 65, 69, 60, 61, 67, 66, 64, 65, 68, 66, 62, 64, 67, 70, 63, 66, 65, 63, 66, 61, 65, 63, 63, 66, 66, 64, 64, 62, 67, 62, 66, 63, 66, 65, 63]
}

def calculate_moments(data, value):
    centered_values = np.array(data) - value
    return {
        "1st Moment": np.mean(centered_values),
        "2nd Moment": np.mean(centered_values**2),
        "3rd Moment": np.mean(centered_values**3),
        "4th Moment": np.mean(centered_values**4)
    }

heights = female_heights["Normal"]
moments = calculate_moments(heights, 75)

print("Moments about 75:")
for moment, value in moments.items():
    print(f"  {moment}: {value:.2f}")

Moments about 75:
  1st Moment: -10.24
  2nd Moment: 111.28
  3rd Moment: -1272.04
  4th Moment: 15184.48

In [91]:
import numpy as np

# Given heights
heights = np.array([  # Convert to NumPy array
    67, 69, 70, 62, 63, 67, 65, 59, 68, 66, 
    60, 65, 67, 63, 64, 65, 69, 60, 61, 67, 
    66, 64, 65, 68, 66, 62, 64, 67, 70, 63, 
    66, 65, 63, 66, 61, 65, 63, 63, 66, 66, 
    64, 64, 62, 67, 62, 66, 63, 66, 65, 63
])

# Calculate moments
mean_height = np.mean(heights)
mu2 = np.mean(heights ** 2) - mean_height ** 2
mu3 = np.mean(heights ** 3) - 3 * mean_height * mu2 - mean_height ** 3
mu4 = np.mean(heights ** 4) - 4 * mean_height * mu3 - 6 * mean_height ** 2 * mu2 + 3 * mean_height ** 4

# Print results
print(f'First Raw Moment (Mean): {mean_height:.2f}')
print(f'Second Central Moment (Variance): {mu2:.2f}')
print(f'Third Central Moment: {mu3:.2f}')
print(f'Fourth Central Moment: {mu4:.2f}')

# Using the moments about 75 for verification
first_moment_about_75 = -10.24  # From your earlier calculation
third_moment_about_75 = -1272.04  # Given
fourth_moment_about_75 = 15184.48  # Given

# Verify the relationships
mu3_verified = third_moment_about_75 - 3 * first_moment_about_75 * mu2 + 2 * (first_moment_about_75 ** 3)
mu4_verified = fourth_moment_about_75 - 4 * first_moment_about_75 * third_moment_about_75 + 6 * (first_moment_about_75 ** 2) * mu2 - 3 * (first_moment_about_75 ** 4)

print(f'Verified Third Central Moment (about 75): {mu3_verified:.2f}')
print(f'Verified Fourth Central Moment (about 75): {mu4_verified:.2f}')

First Raw Moment (Mean): 64.76
Second Central Moment (Variance): 6.42
Third Central Moment: -1.00
Fourth Central Moment: 70353873.97
Verified Third Central Moment (about 75): -3222.23
Verified Fourth Central Moment (about 75): -65863.00