In [3]:
import numpy as np
import pandas as pd
import scipy.stats as stats

data = {
    "Males": [12, 4, 11, 13, 11, 7, 9, 10, 10, 7, 7, 12, 6, 9, 15, 10, 11, 12, 7, 8, 8, 9, 11, 10, 9, 10, 9, 9, 7, 9, 11, 7, 10, 10, 11, 9, 12, 12, 8, 13, 9, 10, 8, 11, 10, 13, 13, 9, 10, 13],
    "Females": [11, 9, 7, 10, 9, 10, 10, 7, 9, 10, 11, 8, 9, 6, 11, 10, 7, 9, 12, 14, 11, 12, 12, 8, 12, 12, 9, 10, 11, 7, 12, 7, 9, 8, 11, 10, 8, 13, 8, 10, 9, 9, 9, 11, 9, 9, 8, 9, 12, 11],
}
df = pd.DataFrame(data)
df

    Males  Females
0      12       11
1       4        9
2      11        7
3      13       10
4      11        9
5       7       10
6       9       10
7      10        7
8      10        9
9       7       10
10      7       11
11     12        8
12      6        9
13      9        6
14     15       11
15     10       10
16     11        7
17     12        9
18      7       12
19      8       14
20      8       11
21      9       12
22     11       12
23     10        8
24      9       12
25     10       12
26      9        9
27      9       10
28      7       11
29      9        7
30     11       12
31      7        7
32     10        9
33     10        8
34     11       11
35      9       10
36     12        8
37     12       13
38      8        8
39     13       10
40      9        9
41     10        9
42      8        9
43     11       11
44     10        9
45     13        9
46     13        8
47      9        9
48     10       12
49     13       11

1.) Formulate and present the rationale for a hypothesis test that the researcher could use to compare the mean time spent on cell phones by male and female college students per week.

Null Hypothesis (𝐻0) = The mean time spent on cell phones is equal for males and females.
FORMULATION FOR NULL HYPOTHESIS:​
𝜇1=𝜇2 (wherein 𝜇1 is the population mean for male students and 𝜇2 is the population mean for female students)

Alternative Hypothesis (H1) = The mean time spent on cell phones differs between males and females.
FORMULATION FOR ALTERNATIVE HYPOTHESIS:
𝜇1≠𝜇2μ (wherein 𝜇1 is the population mean for male students and 𝜇2 is the population mean for female students)

Therefore, with this formulation and rationale, the Null and Alternative Hypothesis that the researcher used, are for comparing the mean time spent on 
cellphones by males and females students in the given dataset per week. (This sets up the context for using a two-sample t-test.)

2.) Analyze the data to provide the hypothesis testing conclusion. What is the p-value for your test? What is your recommendation for the researcher?

In [44]:
import numpy as np
import scipy.stats as stats

Males = [12, 4, 11, 13, 11, 7, 9, 10, 10, 7, 7, 12, 6, 9, 15, 10, 11, 12, 7, 8, 8, 9, 11, 10, 9, 10, 9, 9, 7, 9, 11, 7, 10, 10, 11, 9, 12, 12, 8, 13, 9, 10, 8, 11, 10, 13, 13, 9, 10, 13]
Females = [11, 9, 7, 10, 9, 10, 10, 7, 9, 10, 11, 8, 9, 6, 11, 10, 7, 9, 12, 14, 11, 12, 12, 8, 12, 12, 9, 10, 11, 7, 12, 7, 9, 8, 11, 10, 8, 13, 8, 10, 9, 9, 9, 11, 9, 9, 8, 9, 12, 11]

t_stat, p_value = stats.ttest_ind(Males, Females)
print("T-test:", t_stat)
print("P-value:", p_value)

if p_value < 0.05: 
    print("we are rejecting null hypothesis")
else:
    print("we are accepting null hypothesis")

T-test: 0.30394907866566184
P-value: 0.7618111039906375
we are accepting null hypothesis

Since in the result, p-value resulted greater than 0.05, therefore the researcher fail to reject the null hypothesis, with this result, we can say that 
there is no difference in the mean time spent on cellphones between Males and Females in the sample.

Recommendation to the researcher:
* There may not be an immediate action for the researcher regarding on the cell phone usage based on the gender.
* But, because of the failure in rejecting the null hypothesis test does not proves that the means are equal. I could say that there is not enough
evidence to conclude the difference based on the given dataset.
* The researcher should also interested in the behavior of the dataset, that they need to consider: Like, increasing the sample size ( as this can give a power to detect if difference exist between the two gender in the given dataset) and Exploring other
variables.

3.) (10 points). Provide descriptive statistical summaries of the data for each gender category.

In [27]:
import numpy as np
import pandas as pd

Males = [12, 4, 11, 11, 7, 9, 10, 10, 7, 12, 6, 9, 11, 12, 7, 10, 8, 10, 9, 9, 
         11, 9, 10, 9, 9, 12, 9, 11, 11, 12, 10, 9, 12, 8, 10, 10, 11, 10, 
         9, 12, 12, 8, 11, 7, 9, 11, 13, 9]

Females = [7, 10, 9, 8, 10, 8, 10, 11, 11, 9, 12, 9, 8, 9, 11, 9, 10, 10, 
           11, 12, 10, 9, 10, 12, 9, 13, 8, 9, 7, 10, 12, 11, 9, 9, 11, 
           7, 10, 9, 14, 11, 8, 12, 10, 7, 8, 11, 13, 9, 11, 12]

def descriptive_stats(data):
    stats = {
        "Count": len(data),
        "Mean": np.mean(data),
        "Median": np.median(data),
        "Standard Deviation": np.std(data, ddof=1),
        "Minimum": np.min(data),
        "Maximum": np.max(data),
        "25th Percentile": np.percentile(data, 25),
        "75th Percentile": np.percentile(data, 75),
    }
    return stats

descriptive_stats_males = descriptive_stats(Males)
descriptive_stats_females = descriptive_stats(Females)

stats_df = pd.DataFrame({
    'Males': descriptive_stats_males,
    'Females': descriptive_stats_females
})

print(stats_df)

                        Males    Females
Count               48.000000  50.000000
Mean                 9.750000   9.900000
Median              10.000000  10.000000
Standard Deviation   1.839288   1.681229
Minimum              4.000000   7.000000
Maximum             13.000000  14.000000
25th Percentile      9.000000   9.000000
75th Percentile     11.000000  11.000000

4.) (10 points). What is the 95% confidence interval for the population mean of each gender category, and what is the 95% confidence interval for the difference between the means of the two populations?

In [52]:
def confidence_interval(data, confidence=0.95):
    n = len(data)
    mean = np.mean(data)
    stderr = stats.sem(data)
    interval = stderr * stats.t.ppf((1 + confidence) / 2., n-1)
    return mean - interval, mean + interval

# 95% CI for males
ci_males = confidence_interval(males)
print("95% Confidence Interval for Males:", ci_males)

# 95% CI for females
ci_females = confidence_interval(females)
print("95% Confidence Interval for Females:", ci_females)

# CI for the difference in means
mean_diff = np.mean(males) - np.mean(females)
se_diff = np.sqrt(np.var(males, ddof=1)/len(males) + np.var(females, ddof=1)/len(females))
ci_diff = (mean_diff - 1.96 * se_diff, mean_diff + 1.96 * se_diff)

print("95% Confidence Interval for Difference in Means:", ci_diff)

95% Confidence Interval for Males: (9.215926564918629, 10.284073435081371)
95% Confidence Interval for Females: (9.422200033416297, 10.377799966583703)
95% Confidence Interval for Difference in Means: (-0.8485120355654495, 0.5485120355654488)

5.) (20 points). Do you see a need for larger sample sizes and more testing with the time spent on cell phones? Discuss.

I think, there are 3 factors in discussing this.

1.) Importance of Sample Size:
* Larger sample size increase the statistical power of a study, making it more easy to detect if difference exists.
* The variability is also important, as there are individual differences that can help us to identify if there is an individual differences
* Larger Sample size yield narrower confidence intervals, which could help us to produce a more precise estimates of population parameters.

2.) Current Study Limitations:
* In the given data set, there are 50 participants in each gender, which may not be enough to draw a conclusions regarding on the usage of cellphones
* The generability of the population is also important, if the given data set is not in the broader population, it could be a problem as it could not give us a generalizable findings.

3.) Need For Testing:
* Cellphone usage of the individuals in the given dataset could immediately change as the advancements of the technologies rapidly grew.

6.) (20 points). Make a report including the testing of the assumptions for two independent samples t-test.

In [58]:
import numpy as np
import scipy.stats as stats

# Data
Males = [12, 4, 11, 11, 7, 9, 10, 10, 7, 12, 6, 9, 11, 12, 7, 10, 8, 10, 9, 9, 
         11, 9, 10, 9, 9, 12, 9, 11, 11, 12, 10, 9, 12, 8, 10, 10, 11, 10, 
         9, 12, 12, 8, 11, 7, 9, 11, 13, 9]

Females = [7, 10, 9, 8, 10, 8, 10, 11, 11, 9, 12, 9, 8, 9, 11, 9, 10, 10, 
           11, 12, 10, 9, 10, 12, 9, 13, 8, 9, 7, 10, 12, 11, 9, 9, 11, 
           7, 10, 9, 14, 11, 8, 12, 10, 7, 8, 11, 13, 9, 11, 12]

# 1. Test for Normality using Shapiro-Wilk test
shapiro_males = stats.shapiro(Males)
shapiro_females = stats.shapiro(Females)

# 2. Test for Homogeneity of Variances using Levene's test
levene_test = stats.levene(Males, Females)

# Results
print("Shapiro-Wilk Test for Males: Statistic =", shapiro_males.statistic, ", p-value =", shapiro_males.pvalue)
print("Shapiro-Wilk Test for Females: Statistic =", shapiro_females.statistic, ", p-value =", shapiro_females.pvalue)
print("Levene's Test: Statistic =", levene_test.statistic, ", p-value =", levene_test.pvalue)

Shapiro-Wilk Test for Males: Statistic = 0.9377193983644276 , p-value = 0.01327415172557525
Shapiro-Wilk Test for Females: Statistic = 0.9591843691473334 , p-value = 0.08216562073645903
Levene's Test: Statistic = 0.12028180389546868 , p-value = 0.729488132037419

In [ ]:
Shapiro-Wilk test for Males
With the given result for the test in Males, since the p-value is less than 0.05, therefore the distribution of time spent in cellphone by males is different from normal distribution

Shapiro-Wilk test for Females
With the given result for the test in Females, since the p-value is greater than 0.05, therefore the distribution of time spent in cellphone by females is normally distributed

Levene's Test
Since the p-value is greater than 0.05, therefore we accept the null hypothesis and therefore, the variance